name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: apt helper action
        uses: ryankurte/action-apt@v0.2.0
        with:
          packages: curl wget ca-certificates curl perl python3 python3-dev python-setuptools libgmp10 libgmp-dev locales bash make mawk file pkg-config git
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: |
            ./llvm
          key: llvm-13
      - name: Install LLVM and Clang
        # You may pin to the exact commit or the version.
        # uses: KyleMayes/install-llvm-action@f0cccbdf563688c6e0f9273d4bc27a8c5278de85
        uses: KyleMayes/install-llvm-action@v1.5.3
        with:
          # The version of LLVM and Clang binaries to install.
          version: 13
          # Whether to accept unsupported LLVM and Clang versions.
          force-version: false
      - name: Create chapel directory
        run: |
          export PATH=$PATH:${{ ENV.LLVM_PATH }}/bin
          export CHPL_VERSION=1.26.0
          export CHPL_HOME=/opt/chapel/$CHPL_VERSION

          mkdir -p $CHPL_HOME
          curl -L https://github.com/chapel-lang/chapel/releases/download/$CHPL_VERSION/chapel-$CHPL_VERSION.tar.gz | tar -xzC /opt/chapel --transform 's/chapel-//'

          export CHPL_GMP=system
          export CHPL_LLVM=system
          export CHPL_TARGET_CPU=native
          source $CHPL_HOME/util/setchplenv.bash

          make -j 16 -C $CHPL_HOME
          make -j 16 -C $CHPL_HOME chpldoc test-venv mason

          export PATH=$PATH:$CHPL_HOME/bin/linux64-x86_64:$CHPL_HOME/util
          echo
          echo "------------ Compile Code -------------"
          echo
          make -C ${GITHUB_WORKSPACE}
          echo
          echo "------------ Run Tests -------------"
          echo
          make test -C ${GITHUB_WORKSPACE}
      


